// <auto-generated />
using System;
using EFCore.Snowflake.Metadata;
using EventsApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsApp.Migrations
{
    [DbContext(typeof(SnowflakeContext))]
    [Migration("20260123163756_Refactor")]
    partial class Refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EVENTSAPP")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Snowflake:IndexBehavior", SnowflakeIndexBehavior.Disallow);

            SnowflakeModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsApp.Models.DAT.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"), 1L, 1, false);

                    b.Property<long?>("EventCost")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTCOST");

                    b.Property<string>("EventDesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("EVENTDESC");

                    b.Property<DateTime?>("EventEnd")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENTEND");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("EVENTNAME");

                    b.Property<DateTime?>("EventStart")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENTSTART");

                    b.HasKey("EventId")
                        .HasName("SYS_CONSTRAINT_ac76d4d1-1630-46ef-a5e4-3f4e04cfaddc");

                    b.ToTable("EVENT", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("LOCATIONID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocationId"), 1L, 1, false);

                    b.Property<string>("LocationAddress1")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONADDRESS1");

                    b.Property<string>("LocationAddress2")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONADDRESS2");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONCITY");

                    b.Property<string>("LocationEmail")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONEMAIL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONNAME");

                    b.Property<string>("LocationPhone")
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("LOCATIONPHONE");

                    b.Property<string>("LocationPostCode")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("LOCATIONPOSTCODE");

                    b.Property<string>("LocationRemote")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONREMOTE");

                    b.Property<string>("LocationStateProv")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONSTATEPROV");

                    b.HasKey("LocationId")
                        .HasName("SYS_CONSTRAINT_d082a293-d8bd-4531-8502-d17d075c4562");

                    b.ToTable("LOCATION", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ROLEID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"), 1L, 1, false);

                    b.Property<string>("RoleDesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ROLEDESC");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ROLENAME");

                    b.HasKey("RoleId")
                        .HasName("SYS_CONSTRAINT_4108a80a-0971-4aa5-9238-8887cc26873b");

                    b.ToTable("ROLE", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.SideEvent", b =>
                {
                    b.Property<long>("SideEventId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SideEventId"), 1L, 1, false);

                    b.Property<long?>("SideEventCost")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTCOST");

                    b.Property<string>("SideEventDesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SIDEEVENTDESC");

                    b.Property<string>("SideEventName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("SIDEEVENTNAME");

                    b.HasKey("SideEventId")
                        .HasName("SYS_CONSTRAINT_469cadd1-282a-496d-9d63-d8f3690a375a");

                    b.ToTable("SIDEEVENT", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Team", b =>
                {
                    b.Property<long>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("TEAMID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeamId"), 1L, 1, false);

                    b.Property<string>("TeamName")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("TEAMNAME");

                    b.HasKey("TeamId")
                        .HasName("SYS_CONSTRAINT_f9bfe607-791d-4386-87f0-5861a9a8c56a");

                    b.ToTable("TEAM", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1, false);

                    b.Property<string>("FName")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("FNAME");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LNAME");

                    b.HasKey("UserId")
                        .HasName("SYS_CONSTRAINT_95fad561-982d-4f4a-976d-8eefc31552d0");

                    b.ToTable("USER", "EVENTSAPP_DAT");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventLocation", b =>
                {
                    b.Property<long?>("EventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("LocationId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("LOCATIONID");

                    b.ToTable("EVENTLOCATION", "EVENTSAPP_MAP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEvent", b =>
                {
                    b.Property<long?>("EventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("SideEventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    b.ToTable("EVENTSIDEEVENT", "EVENTSAPP_MAP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEventUser", b =>
                {
                    b.Property<long?>("EventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("SideEventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    b.Property<long?>("UserId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("EVENTSIDEEVENTUSER", "EVENTSAPP_MAP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventTeamUser", b =>
                {
                    b.Property<long?>("EventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("TeamId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("TEAMID");

                    b.Property<long?>("UserId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("MAP_EVENTTEAMUSER", "EVENTSAPP_MAP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventUser", b =>
                {
                    b.Property<long?>("EventId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("UserId")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("MAP_EVENTUSER", "EVENTSAPP_MAP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventLocation", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTLOCATION_EVENTID");

                    b.HasOne("EventsApp.Models.DAT.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTLOCATION_LOCATIONID");

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEvent", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENT_EVENTID");

                    b.HasOne("EventsApp.Models.DAT.SideEvent", "SideEvent")
                        .WithMany()
                        .HasForeignKey("SideEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENT_SIDEEVENTID");

                    b.Navigation("Event");

                    b.Navigation("SideEvent");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEventUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSER_EVENTID");

                    b.HasOne("EventsApp.Models.DAT.SideEvent", "SideEvent")
                        .WithMany()
                        .HasForeignKey("SideEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSER_SIDEEVENTID");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSER_USERID");

                    b.Navigation("Event");

                    b.Navigation("SideEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventTeamUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSER_EVENTID");

                    b.HasOne("EventsApp.Models.DAT.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSER_TEAMID");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSER_USERID");

                    b.Navigation("Event");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTUSER_EVENTID");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTUSER_USERID");

                    b.Navigation("Event");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
