// <auto-generated />
using System;
using EFCore.Snowflake.Metadata;
using EventsApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsApp.Migrations
{
    [DbContext(typeof(SnowflakeContext))]
    [Migration("20260123152332_Correct Table Names")]
    partial class CorrectTableNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EVENTSAPP")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Snowflake:IndexBehavior", SnowflakeIndexBehavior.Disallow);

            SnowflakeModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsApp.Models.DAT.Event", b =>
                {
                    b.Property<long>("Eventid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Eventid"), 1L, 1, false);

                    b.Property<long?>("Eventcost")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTCOST");

                    b.Property<string>("Eventdesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("EVENTDESC");

                    b.Property<DateTime?>("Eventend")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENTEND");

                    b.Property<string>("Eventname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("EVENTNAME");

                    b.Property<DateTime?>("Eventstart")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENTSTART");

                    b.HasKey("Eventid")
                        .HasName("SYS_CONSTRAINT_ac76d4d1-1630-46ef-a5e4-3f4e04cfaddc");

                    b.ToTable("EVENT", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Location", b =>
                {
                    b.Property<long>("Locationid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("LOCATIONID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Locationid"), 1L, 1, false);

                    b.Property<string>("Locationaddress1")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONADDRESS1");

                    b.Property<string>("Locationaddress2")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONADDRESS2");

                    b.Property<string>("Locationcity")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONCITY");

                    b.Property<string>("Locationemail")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONEMAIL");

                    b.Property<string>("Locationname")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LOCATIONNAME");

                    b.Property<string>("Locationphone")
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("LOCATIONPHONE");

                    b.Property<string>("Locationpostcode")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("LOCATIONPOSTCODE");

                    b.Property<string>("Locationremote")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONREMOTE");

                    b.Property<string>("Locationstateprov")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LOCATIONSTATEPROV");

                    b.HasKey("Locationid")
                        .HasName("SYS_CONSTRAINT_d082a293-d8bd-4531-8502-d17d075c4562");

                    b.ToTable("LOCATION", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Role", b =>
                {
                    b.Property<long>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ROLEID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Roleid"), 1L, 1, false);

                    b.Property<string>("Roledesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ROLEDESC");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ROLENAME");

                    b.HasKey("Roleid")
                        .HasName("SYS_CONSTRAINT_4108a80a-0971-4aa5-9238-8887cc26873b");

                    b.ToTable("ROLE", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.SideEvent", b =>
                {
                    b.Property<long>("Sideeventid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sideeventid"), 1L, 1, false);

                    b.Property<long?>("Sideeventcost")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTCOST");

                    b.Property<string>("Sideeventdesc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SIDEEVENTDESC");

                    b.Property<string>("Sideeventname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("SIDEEVENTNAME");

                    b.HasKey("Sideeventid")
                        .HasName("SYS_CONSTRAINT_469cadd1-282a-496d-9d63-d8f3690a375a");

                    b.ToTable("SIDEEVENT", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.Team", b =>
                {
                    b.Property<long>("Teamid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("TEAMID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Teamid"), 1L, 1, false);

                    b.Property<string>("Teamname")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("TEAMNAME");

                    b.HasKey("Teamid")
                        .HasName("SYS_CONSTRAINT_f9bfe607-791d-4386-87f0-5861a9a8c56a");

                    b.ToTable("TEAM", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.DAT.User", b =>
                {
                    b.Property<long>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Userid"), 1L, 1, false);

                    b.Property<string>("Fname")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("FNAME");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("LNAME");

                    b.HasKey("Userid")
                        .HasName("SYS_CONSTRAINT_95fad561-982d-4f4a-976d-8eefc31552d0");

                    b.ToTable("USER", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventLocation", b =>
                {
                    b.Property<long?>("Eventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("Locationid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("LOCATIONID");

                    b.ToTable("MAP_EVENTLOCATION", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEvent", b =>
                {
                    b.Property<long?>("Eventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("Sideeventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    b.ToTable("MAP_EVENTSIDEEVENT", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEventUser", b =>
                {
                    b.Property<long?>("Eventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("Sideeventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("SIDEEVENTID");

                    b.Property<long?>("Userid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("MAP_EVENTSIDEEVENTUSER", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventTeamUser", b =>
                {
                    b.Property<long?>("Eventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("Teamid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("TEAMID");

                    b.Property<long?>("Userid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("MAP_EVENTTEAMUSER", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventUser", b =>
                {
                    b.Property<long?>("Eventid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("EVENTID");

                    b.Property<long?>("Userid")
                        .HasPrecision(38)
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("USERID");

                    b.ToTable("MAP_EVENTUSER", "EVENTSAPP");

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventLocation", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTLOCATIONEVENTID");

                    b.HasOne("EventsApp.Models.DAT.Location", "Location")
                        .WithMany()
                        .HasForeignKey("Locationid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTLOCATIONLOCATIONID");

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEvent", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTEVENTID");

                    b.HasOne("EventsApp.Models.DAT.SideEvent", "Sideevent")
                        .WithMany()
                        .HasForeignKey("Sideeventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTSIDEEVENTID");

                    b.Navigation("Event");

                    b.Navigation("Sideevent");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventSideEventUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSEREVENTID");

                    b.HasOne("EventsApp.Models.DAT.SideEvent", "Sideevent")
                        .WithMany()
                        .HasForeignKey("Sideeventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSERSIDEEVENTID");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTSIDEEVENTUSERUSERID");

                    b.Navigation("Event");

                    b.Navigation("Sideevent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventTeamUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSEREVENTID");

                    b.HasOne("EventsApp.Models.DAT.Team", "Team")
                        .WithMany()
                        .HasForeignKey("Teamid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSERTEAMID");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTTEAMUSERUSERID");

                    b.Navigation("Event");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventsApp.Models.MAP.EventUser", b =>
                {
                    b.HasOne("EventsApp.Models.DAT.Event", "Event")
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTUSEREVENTIDFK");

                    b.HasOne("EventsApp.Models.DAT.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("EVENTUSERUSERIDFK");

                    b.Navigation("Event");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
